package BdData;


my $data = {
'blated' => [
	q|Happy belated birthday!|,
	q|How do you expect me to remember your birthday, when you never look any older?|,
	q|I hope your birthday was all that you hoped for.|,
	q|Wishing you a belated birthday.|,
	q|I am sorry I missed your birthday, you have had so many I lost track.|,
	q|I hope your birthday was as special as you are.|,
	q|Happy <s>belated</s> early birthday!|,
	q|Sorry I forgot the most important day of the year... your birthday!|,
	q|2, 4, 6, 8, sorry that this birthday cheer is late!|,
	q|This wish is late so that you can celebrate your birthday longer.|,
	q|I'm so lucky to have such a great friend like you... who'd forgive me if I forgot his(/her) birthday. Happy belated birthday!|,
	q|Best wishes for your birthday afterwards.|,
	q|I hope all your birthday wishes came true.|,
	q|Even though this message comes to you a little late, the wish it brings for happiness is good on any day date. Happy belated birthday.|,
	q|The bad news is that I forgot to wish you a happy birthday on time. The good news is I forgot your age.|,
	q|I didn't forget about your birthday; I just wanted to help prolong the celebration.|,
	q|Your birthday came and went<br>Here's the card I should have sent|,
	q|I didn't really forget your special day, I just figured you deserved more than one.|,
	q|Fashionably late. Hope it was great.|,
	q|I may have forgotten your birthday, but at least I remember that I forgot your birthday.|,
	q|I didn't forget your birthday, I'm just fashionably late.|,
	q|I'm so sorry I missed your birthday, I hope that you had a wonderful day.|,
	q|I may have forgotten your birthday, but I didn't forget about you!|,
	q|Happy belated birthday to someone who now has free reign to forget mine.|,
	q|Don't hate me because I forgot your birthday. Hate me because I'm beautiful.|,
	q|It feels like you just had a birthday the other day. Oh yeah, sorry I am late. Happy birthday.|,
	q|My best wishes to you, even though are belated.|,
	q|I might have forgotten your birthday, but at least I got a gift for you.|,
	q|Better late than never? Hope you had the most amazing birthday.|,
	q|Sorry I forgot your birthday. Can you reschedule it for sometime next week?|,
	q|Roses are red<br>Violets are blue<br>Sorry these wishes are so overdue<br>Happy belated birthday|,
	q|Sorry I forgot your birthday, my memory gets worst year after year. I think you understand what I'm talking about.|,
	q|Sorry I missed your birthday. I swear that this only happens to me like once a year.|
],
'funny' => [
	q|Happy birthday, you're not getting older you're just a little closer to death.|,
	q|To the nation's best kept secret; your true age.|,
	q|Birthdays are like boogers, the more you have the harder it is to breathe.|,
	q|Birthdays are good for you. Statistics show that people who have the most live the longest!|,
	q|Money's tight<br>Times are hard<br>Here's you friggin birthday card|,
	q|Growing old is mandatory; growing up is optional.|,
	q|Better to be over the hill than buried under it.|,
	q|You always have such fun birthdays; you should have one every year.|,
	q|So many candles... so little cake.|,
	q|Happy birthday to a person who is smart, good looking, and funny and reminds me a lot of myself.|,
	q|We know we're getting old when the only thing we want for our birthday is not to be reminded of it.|,
	q|Happy birthday on your very special day, I hope that you don't die before you eat your cake.|,
	q|Stop counting the candles and start thinking about your wishes.|,
	q|You're a hard person to shop for, so I didn't get you anything. Happy birthday.|,
	q|Wishing you many more candles and a cake big enough to fit them all on.|,
	q|You're another year older and another year wiser<br>So put your brain to work<br>And figure out there ain't no gift for you.|,
	q|Two tips on your birthday:<br>1) Forget the past, you can't change it.<br>2) Forget the present, I didn't get you one.|,
	q|Some words of wisdom for your birthday, "Smile while you still have teeth!"|,
	q|Happy birthday you old fart.|,
	q|You would have loved the gift I didn't bother getting you.|,
	q|Another year, another new place thet aches.|,
	q|One more year of existence down the drain. Happy birthday!|,
	q|The only reason you hate your birthday is because people give you odd gifts, scary cards with weird messages in them, and because you're getting older. Anyway, happy birthday!|,
	q|It's ok to light the candles on your birthday cake now; I've already alerted the fire department.|,
	q|With age comes wisdom. (You're one of the wisest people I know!)|,
	q|I was trying to think of what to get you for your birthday but nothing came to mind.|,
	q|You're not old until you can't read this writing anymore. (written in real small text)|,
	q|Hoping you dance the night away or at least watch other people dance late into the night, or at least stay awake...|,
	q|Hoping that you can find all the strength and courage needed... to blow all of the candles out.|,
	q|You have reached the age where all compliments will be followed by, "For someone your age."|,
	q|Don't think of it as getting older, think of it as becoming a classic.|,
	q|An old fart is as good as a new one.|,
	q|You've survived another year. Although you're older, it's better than the alternative. Congratulations!|,
	q|You age like cheese... You just keep getting smellier!|,
	q|Is it getting hotter in here or is it just all the candles on your cake?|,
	q|There were a lot of famous people born on your birthday. Too bad you aren't one.|,
	q|The younger you try to look; the older you actually are.|,
	q|Another year older, none the wiser.|,
	q|Happy birthday to you<br>You live in a zoo<br>You look like a monkey<br>And you smell like one too|,
	q|Enjoy your birthday cake today since tomorrow we'll return to judging you based on every single morsel you ingest.|
],
'inspirational' => [
	q|Hoping that your day will be as special as you are.|,
	q|I'm so glad you were born, because you brighten my life and fill it with joy.|,
	q|Count your life by smiles, not tears.<br>Count your age by friends, not years.|,
	q|May the years continue to be good to you. Happy birthday!|,
	q|You're not getting older, you're getting better.|,
	q|May this year bring with it all the success and fulfillment your heart desires.|,
	q|Wishing you all the great things in life, hope this day will bring you an extra share of all that makes you happiest.|,
	q|Happy birthday, and may all the wishes and dreams you dream today turn to reality.|,
	q|May this day bring to you all things that make you smile. Happy birthday!|,
	q|Your best years are still ahead of you.|,
	q|Birthdays are filled with yesterday's memories, today's joys, and tomorrow's dreams.|,
	q|You'll always be forever young.|,
	q|Some things get better with age ... you're one of them! Happy birthday.|,
	q|Remember that today many people are glad you were born.|,
	q|A lot of things get better with the years... and you are one of them.|,
	q|No one can hold a candle to you. Happy birthday!|,
	q|Today is your day to shine as every day should be. Happy birthday!|,
	q|I hope that your birthday is as wonderful as you are.|,
	q|God gave a gift to the world when you were born; a person who loves and cares, who sees a person's need and fills it, who encourages and lifts people up, who spends energy on others rather than himself, who touches each life he enters & makes a difference in the world. May the love you have shown to others return to you multiplied.|,
	q|Don't count the years, count the blessings.|,
	q|Wishing you a year filled with the same joy you bring to others.|,
	q|Wishing you all the best in the year to come. May your days be filled with sunshine and beautiful colors. And may your nights be filled with comforting dreams and wishes to come.|,
	q|No one desrves a happier birthday than you.|,
	q|Youth happens, but age is earned.|,
	q|Days have passed into years, you have become better with time. May you continue to become better with each birthday you enjoy.|,
	q|Happy birthday<br>You are very special<br>And you deserve the best<br>I wish you a wonderful life<br>Filled with love and happiness|,
	q|It must have been a rainy day when you were born because the heavens were crying because it lost its most beautiful angel.|,
	q|Life is great at any age so enjoy yours. Happy birthday.|,
	q|Don't count the years, count all the cheers.|,
	q|Happy birthday, you don't look as old as your age.|,
	q|Age is not a destination, it's a journey!|,
	q|Happy birthday to someone who has given much happiness to so many.|,
	q|On your birthday; Count your candles, count your years, count your blessings.|,
	q|Thank you for always just being you. Happy birthday.|,
	q|You grow more beautiful with each passing year. Happy birthday.|,
	q|Many things have changed over the years but you're still the same great person you always have been.|,
	q|Every year that passes is another stepping stone to greatness.|,
	q|Hope you have your cake and eat it too! Happy birthday!|,
	q|Some things are good from the start while others get better with time. You started great and soared even higher.|,
	q|I hope you enjoy your birthday as much as I have enjoyed you.|
],
'love' => [
	q|Thinking of you with love on your birthday and wishing you everything that brings you happiness today and always.|,
	q|To the world, you may be one person, but to me, you are the world.|,
	q|It's as easy to stay in love with you as it was to fall in love.|,
	q|Happy birthday my love!|,
	q|It is not being in love that makes me happy but it is being in love with YOU that makes me happy.|,
	q|With each year I love you more and more.|,
	q|I'm enthralled by your beauty, mesmerised by your charisma and spellbound by your love. No wonder I am always thinking about you.|,
	q|It's always a treat to wish happy birthday to someone so sweet.|,
	q|My heart for you will never break. My smile for you will never fade. My love for you will never end. I love you.|,
	q|Happy birthday my dearest and sweetest, not a day goes by when I do not think of you and how empty my life would be if you were not here.|,
	q|With each year I'll love you more. Remember that your best years are still ahead of you and I'll be there for every up down and in between.|,
	q|Because you're the gift in my life, I give you my gift of love.|,
	q|Being in love doesn't make me happy. It's being in love with you year after year that does the trick.|,
	q|I searched my wallet and found it empty<br>I searched my pockets and found some few coins<br>Then I searched my heart and I found you<br>Then I realized how rich I am<br>Happy birthday!|,
	q|Sometimes words are hard to find to form that perfect line to let you know you are always on my mind. Happy birthday dear!|,
	q|Happy birthday my love. I'm so glad we're spending it together.|,
	q|I love you more than I did yesterday, but not as much as I will tomorrow.|,
	q|I am so glad that I can share this special day with my favorite person.|,
	q|Sending you my love on your birthday and everyday.|,
	q|It takes only a few seconds to say I love you but it will take me an entire lifetime to show you how much.|,
	q|You get lots of greetings for your birthday but this one comes to you with all of my love.|,
	q|It's not important that this day is your birthday. It's important that everyday is your day and you are mine!|,
	q|Next to you is one of my favorite places to be. Happy birthday.|,
	q|Falling in love with you was easy. Staying in love with you is easier. Happy birthday. I can't wait until next year.|,
	q|It must have been a rainy day when you were born because the heavens were crying because it lost its most beautiful angel.|,
	q|Much love on your birthday and always.|,
	q|When we're together or when we're apart, you're first in my thoughts and first in my heart. Have a wonderful birthday.|,
	q|I feel so lucky sharing my life with someone as wonderful as you.|,
	q|Happy birthday to someone who makes me truly happy.|,
	q|<a href=http://www.greatromanticideas.com target=_blank>Great Romantic Ideas</a>|
],
'poems' => [
	q|Hope lovely surprises are coming your way<br>To make your birthday a wonderful day|,
	q|Smiles and laughter, joy and cheer<br>New happiness that stays throughout the year<br>Hope your birthday brings all these and more<br>Filling life with surprise and joys galore!|,
	q|So on this very special day<br>I would like to say to you<br>I hope you'll always find happiness<br>In whatever you may do.|,
	q|Another candle on your cake<br>Well there's no need to pout<br>Be glad that you have strength enough<br>To blow them all out!|,
	q|Wishing you your happiest birthday yet.<br>A birthday too special to ever forget.|,
	q|So many wishes<br>So many smiles<br>Too many memories<br>Too few words<br>With one big birthday<br>Happy birthday!|,
	q|It's your birthday and I can't be there<br>But I'll send you a special birthday wish and a little prayer<br>Have a happy birthday<br>I hope that all of your birthday wishes come true<br>May you have a great time today and find happiness in everything you do.|,
	q|Happy birthday form the heart<br>Cause that's where all great wishes start|,
	q|May your birthday be happy<br>And then through the year<br>May God bless and guide you<br>And always be near|,
	q|You're birthday is here<br>You're getting old<br>But you're still my dear!|,
	q|Cake...<br>Eat a little<br>Eat a lot<br>Eat untill you have to stop!|,
	q|I hope that you have the best birthday that you could wish for<br>And I hope that the candles on your cake go out with your first puff<br>For then your wish will come sparkling true!|,
	q|Roses are red<br>Violets are blue<br>Stop complaining... I am older than you!|,
	q|Today is your day to celebrate<br>Your day to be the star<br>So let the ones you love all cheer<br>And say how special you are|,
	q|Happy happy birthday<br>Today's your special day<br>You just got a cupcake<br>So blow the flame away|,
	q|Hope your birthday is full of fun<br>From the second it starts<br>Till the second it's done|,
	q|Instead of counting candles<br>Or tallying the years<br>Contemplate your blessings now<br>As your birthday nears|,
	q|May your troubles be less and your blessings be more<br>And nothing but hapiness come through your door|,
	q|May your day be filled with hugs, kisses and birthday wishes<br>May your birthday not be forgotten<br>And that you be spoiled rotten<br>But most of all today is your birthday, so hip hip hooray!|,
	q|Roses are red violets are blue<br>This poem is your present<br>So whoo hoo!|
],
'quotes' => [
	q|Our birthdays are feathers in the broad wing of time.<br>- Jean Paul Richter|,
	q|Inside every older person is a younger person wondering what happened.<br>- Jennifer Yane|,
	q|Wisdom doesn't necessarily come with age. Sometimes age just shows up all by itself.<br>- Tom Wilson|,
	q|May you stay forever young.<br>- Bob Dylan|,
	q|The old believe everything; the middle-aged suspect everything; the young know everything.<br>- Oscar Wilde|,
	q|Old age is like everything else. To make a success of it, you've got to start young.<br>- Fred Astaire|,
	q|Age is a number and mine is unlisted.<br>- Unknown|,
	q|When I was younger, I could remember anything, whether it happened or not.<br>- Mark Twain|,
	q|Whatever with the past has gone, The best is always yet to come.<br>- Lucy Larcom|,
	q|It takes a long time to grow young.<br>- Pablo Picasso|,
	q|Few women admit their age. Few men act theirs.<br>- Unkown|,
	q|The best way to remember your wife's birthday is to forget it once.<br>- H. V. Prochnow|,
	q|Men are like wine. Some turn to vinegar, but the best improve with age.<br>- C.E.M. Joad|,
	q|The first hundred years are the hardest.<br>- Wilson Mizner|,
	q|Youth is the gift of nature, but age is the work of art.<br>- Garson|,
	q|You know you are getting old when the candles cost more than the cake.<br>- Bob Hope|,
	q|Youth has no age.<br>- Pablo Picasso|,
	q|Age is a high price to pay for maturity.<br>- Tom Stoppard|,
	q|Age is an issue of mind over matter. If you don't mind, it doesn't matter.<br>- Mark Twain|,
	q|We grow too soon old and too late smart.<br>- Pennsylvania Dutch proverb|,
	q|If I'd known I was going to live this long, I'd have taken better care of myself.<br>- Ubie Blake|,
	q|Let us respect gray hairs, especially our own.<br>- J. P. Sears|,
	q|Time flies like an arrow. Fruit flies like a banana.<br>- Groucho Marx|,
	q|All the world is birthday cake, so take a piece, but not too much.<br>- George Harrison|,
	q|And in the end, it's not the years in your life that count. It's the life in your years.<br>- Abraham Lincoln|,
	q|Growing old is mandatory; growing up is optional.<br>- Chili Davis|,
	q|You are only young once, but you can be immature for a lifetime.<br>- John P. Grier|,
	q|The secret of staying young is to live honestly, eat slowly, and lie about your age.<br>- Lucille ball|,
	q|Old age isn't so bad when you consider the alternatives.<br>- Maurice Chevalier|,
	q|Pleas'd to look forward, pleas'd to look behind,<br>And count each birthday with a grateful mind.<br>- Alexander Pope|,
	q|The more things change, the more they remain the same.<br>- Alphonse Karr|,
	q|The best birthdays of all are those that haven't arrived yet.<br>- Robert Orben|,
	q|It is lovely, when I forget all birthdays, including my own, to find that somebody remembers me.<br>- Ellen Glasgow|,
	q|As you get older three things happen. The first is your memory goes, and I can't remember the other two.<br>- Sir Norman Wisdom|,
	q|You are never too old to set another goal or to dream a new dream.<br>- Les Brown|,
	q|There are three hundred and sixty-four days when you might get un-birthday presents and only one for birthday presents, you know.<br>- Lewis Carroll|,
	q|Last week the candle factory burned down. Everyone just stood around and sang "Happy Birthday."<br>- Stephen Wright|,
	q|Nice to be here?  At my age it's nice to be anywhere.<br>- George Burns|,
	q|Aging seems to be the only available way to live a long life.<br>- Daniel Francois Esprit Auber|,
	q|How far that little candle throws his beams!<br>- William Shakespeare|,
	q|<a href=http://www.happybirthdayquotes.com>More Birthday Quotes</a>|
],
'religious' => [
	q|May God continue to bless you life and give you the desires of your heart.|,
	q|May God bless you and keep you always in His tender, loving care.|,
	q|I hope that your day is blessed with happiness and joy.|,
	q|You're the kind of friend that only heaven could have sent.|,
	q|Praying that your day is as special as you are.|,
	q|May you enjoy the Lord's presence today.|,
	q|As God adds life to your years, may He add years to your life. Happy birthday!|,
	q|May the good Lord shower you with many blessings on your special day.|,
	q|God is so wise that he never created friends with price tags. If He did, I wouldn't have been able to afford a precious friend like you.|,
	q|May God grant you the strength to blow out all those candles on your cake.|,
	q|May God soften the pillow you rest your head on at night|,
	q|May He make smooth the path you walk by day|,
	q|Not just today but everyday|,
	q|I thank God for the day that you were born and for you being such a great friend to me.|,
	q|Here's to another year of blessings!|,
	q|May God bless your birthday and fill your life with His love.|,
	q|Today and throughout every season, may God's grace give you every possible reason to smile, to enjoy and to celebrate.|,
	q|Happy birthday to you my friend. May you include God in all you do. Thank Him for giving again a new life. Today is the time to fulfill your dreams because God has given you a chance to change and to do better than before.|,
	q|A special prayer for you that the Lord will bless you on your special day.|,
	q|May god continue to bless you and use you in all of his ways. Happy b'day.|,
	q|May God bless you more and more with each passing year.|,
	q|It's your birthday and I can't be there but I'll send you a special birthday wish and a little prayer.|,
	q|No sorrows to depress you, only shadows to surround you, God himself to bless you. Happy birthday!|,
	q|Wishing you a blessed birthday!|,
	q|It is clear that God created you for a great purpose. Happy birthday!|,
	q|Don't pray for forgiveness for eating too much cake, just exercise more.|,
	q|Wishing you a happy birthday. May God bless you all the days you live.|,
	q|Happy birthday to you. I pray to God that He blesses you today and gives you strength to have positive thoughts and to give you success in your life.|,
	q|May God bless you on your birthday and everyday in every way.|
],
'wishes' => [
	q|The more candles, the bigger the wish.|,
	q|Wishing you everything happy for your birthday.|,
	q|Wishing you miles of smiles in the coming years.|,
	q|Wishing you all the best for your birthday.|,
	q|May all your dreams and wishes come true!|,
	q|Wishing you all the fun and excitement that only birthdays can bring.|,
	q|Wishing you all the best on your speacial day.|,
	q|Wishing you a happy birthday, from the bottom of my heart.|,
	q|Best wishes on your birthday and throughout the coming year.|,
	q|Wishing you a happy birthday and many more to come.|,
	q|May the best of your wishes be the least of what you get.|,
	q|Wishing you a happy and prosperous birthday and a sweet night of birthday dreams.|,
	q|Wishing you all your favorite things for your birthday.|,
	q|I've waited 364 days to wish you a happy birthday.  Happy birthday!|,
	q|Wishing you everything happy today and always.|,
	q|Wishing you many more happy years to come. Happy birthday!|,
	q|Wishing you all the best in the year to come.<br>May your days be filled with sunshine and beautiful colors.<br>And may your nights be filled with comforting dreams and wishes to come.|,
	q|Although I can't wish you a happy birthday in person; I will spend the whole day with happy thoughts of you.|,
	q|Wishing you many more good and prosperous years.|,
	q|Wishing you good health and happiness in life.|,
	q|Hoping your wishes come true year after year.|,
	q|On your birthday, may every glowing candle on your cake be a wish that comes true.|,
	q|Hope your birthday blossoms into lots of dreams come true.|,
	q|Wishing you a very warm birthday.|,
	q|Wishing you only the best on your special day.|,
	q|Wishing you the happiest of birthdays; Hope this is your best year yet.|,
	q|Wishing you many more candles to come. Happy birthday.|,
	q|Wishing you many bright and happy days throughout this upcoming new year. Happy birthday.|,
	q|Wishing you the loveliest of birthdays.|,
	q|Thinking of you on your birthday and wishing you much happiness.|,
	q|Wishing you all of the happiness that you deserve.|,
	q|Wishing you the best birthday ever.|,
	q|Wishing you happiness for your birthday and every day.|,
	q|May all your wishes and dreams you dream today turn to reality.|,
	q|Happy birthday! Hope all your wishes come true.|,
	q|Wishing an amazing day and many great things to come to a wonderful person. Happy birthday.|,
	q|Best wishes for a happy day filled with laughter and love.|,
	q|On your birthday, may every glowing candle on your cake be a wish that comes true.|,
	q|Wishing you a cheerful birthday.|,
	q|Wishing you lots of happy suprises for your birthday.|
],
};

$main::bdata=$data;

1;

